### ISSUE TITLE
Missing things 

### ISSUE THREAD

**Issue by SaphirRose** [cnlohr/donut#1]
Left light has white base with broken off light. No light in bag. Back has back rectangle outline where 3 holes are and nothing attached. No idea who to contact

**Comment by jasonspriggs** [comment]
Hi! Can you attach a photo of the broken off light so we know? The rectangle outline on the back is where you can solder on a headphone jack if you're so inclined. It's shipped unpopulated.

**Comment by jasonspriggs** [comment]
Resolved in email.

**Comment by cnlohr** [comment]
aww I was hoping you'd post the digikey part number for the headphone jack.

**Comment by dylwhich** [comment]
https://www.digikey.com/product-detail/en/cui-inc/MJ-3536N/CP-3536N-ND/281264

**Comment by cnlohr** [comment]
It is now documented.
